version: '2'
services:
  mysql:
    build: ./mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  php:
    build: ./php
    ports:
      - '80:80'
    volumes:
      - ./load_test_app:/var/www/html
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.10.112"
volumes:
  db:
